backend:
  name: github
  repo: TUUSUARIO/TUREPO   # reemplaza con tu usuario y repo en GitHub
  branch: main

media_folder: "static/images"   # dónde se guardan las imágenes en tu repo
public_folder: "/images"

collections:
  - name: "contenido"
    label: "Contenido principal"
    files:
      - file: "content/textoentrada.yml"
        label: "Texto Liderazgo"
        name: "textoentrada"
        fields:
          - {label: "Texto debajo del título", name: "texto", widget: "text"}

      - file: "content/imagenautor.yml"
        label: "Imagen Autor"
        name: "imagenautor"
        fields:
          - {label: "Foto del autor", name: "photo", widget: "image"}
